### ISSUE TITLE
Add AddServiceProbe<T> to nuget package

### ISSUE THREAD

**Issue by rikbosch** [OrleansContrib/OrleansTestKit#10]
Hi,

Is it possible to release an new nuget version with TestServiceProvider support?

**Comment by dsarfati** [comment]
@rikbosch I'm looking into getting AppVeyor to automatically push updated packages to nuget, so I should have a new version released today. Thanks for contributing!

**Comment by dsarfati** [comment]
Done! You should be able to use 0.1.1 that includes everything that is in master. Let me know if you have problems
