### ISSUE TITLE
It.IsAny<Id>

### ISSUE THREAD

**Issue by freever** [OrleansContrib/OrleansTestKit#101]
Hi guys

Is there any way to configure TestKitSilo to return a mock grain when it is called with _any_ id? 

I have a case where a grain will generate a new Guid and then activate a grain of another type using that new Guid in order to create a new instance of the target grain. 

Thinking in terms of MoqI would use something like It.IsAny<Guid>() but TestKitSilo requires an actual Id. Since I am Guid.NewGuidding it inside my grain I can't inject a predetermined id without doing a lot of unnecessary factory stuff. 

Is there any way to achieve this currently?

Thanks!

**Comment by jkonecki** [comment]
The way I achieve it is by storing newly-generated Id in grain state (I need it in grain state anyway).

In the unit test I can fetch the Id from state and access new grain mock.

Another option (I think, not sitting in front of the code now) would be to enumerate all mocks (reflection magic may be needed) and find the one of the type of the new grain.

**Comment by freever** [comment]
I think my problem is that I need to know the Id at setup time because I need to configure the mock grain to return certain values at runtime. I have resorted to using an IdFactory in cases where this is needed for me.

**Comment by seniorquico** [comment]
I'd be open to a bit of a design discussion around this... I believe we hit it in a couple of projects in the past, and I resorted to `TestCluster`-based testing for these types of scenarios. I can see some potential for scaffolding a grain without knowing its unique identifier upfront. Do you have an API proposal? Additionally, what if the grain under test creates multiple, new grains of the same type? A bit of an edge case, but if there were an `It.IsAny<Id>` resolver, would these all resolve to a single instance?

**Comment by freever** [comment]
@seniorquico I did some more digging in the code and found something that might work. I have inadvertently refactored away from needing to do this, but there appears to be a way to configure the TestGrainFactory using a factory func instead of an id:

```c#
void AddProbe<T>(Func<IGrainIdentity, IMock<T>> factory)
```

So I guess in theory we could do something like this.

Given this grain:

```c#
public interface IMysteryGrain : IGrainWithGuidKey
{
     Task<Guid> WhoAreYou();
     Task<string> WhyAreYou();
}
```

We could set up a queue to return mocks in a sequence:

```c#
var firstMock = new Mock<IMysteryGrain>();
firstMock.Setup(x => x.WhyAreYou()).ReturnsAsync("dunno");

var secondMock = new Mock<IMysteryGrain>();
secondMock.Setup(x => x.WhyAreYou()).ReturnsAsync("becos");

var mocks = new Queue<Mock<IMysteryGrain>>(new[] {firstMock, secondMock});
```

Then configure the TestKitSilo to return the next mock in sequence and even configure it with some setup based on the grain id it is given:

```c#
Silo.AddProbe(id =>
{
    var mock = mocks.Dequeue();
             
    mock.Setup(x => x.WhoAreYou())
        .ReturnsAsync(id.PrimaryKey);
              
    return mock;
});
```

And then confirm that things happened.

```c#
firstMock.Verify(x => x.WhoAreYou(), Times.Once);
secondMock.Verify(x => x.WhoAreYou(), Times.Once);
```

So I'm not sure if this will work or not, but it looks like it should and I will give it a try next time I need this.

**Comment by freever** [comment]
Actually, I just had another need for this and it worked, at least in a simiplified scenario:

```c#
//Arrange
var newUserDeviceNotificationsGrain = new Mock<IDeviceNotificationsGrain>();
Silo.AddProbe(x => newUserDeviceNotificationsGrain);
 
//Assert
//blah

//Assert
newUserDeviceNotificationsGrain.Verify(x => //blah );

```

**Comment by seniorquico** [comment]
Very neat, @freever! 🎉

We lack official docs, but we generally try to document how to use the TestKit with unit tests. Do you think you'd have some time to create a new test suite with different cases that show off a few different ways this strategy could be applied? Maybe a simplified case where the grain needs to create just one other grain, and maybe a more complex case where the grain uses your `Queue` strategy where the grain needs to create multiple other grains?

**Comment by freever** [comment]
Will do!

**Comment by seniorquico** [comment]
Thanks @freever for contributing this example and a new test case!
