### ISSUE TITLE
TestStream OnNextBatchAsync

### ISSUE THREAD

**Issue by michaeltdaniels** [OrleansContrib/OrleansTestKit#107]
Are there any plans to support OnNextBatchAsync in TestStream?
https://github.com/OrleansContrib/OrleansTestKit/blob/f279cfc3d81dc64a30425cc18280c7bd3558d546/src/OrleansTestKit/Streams/TestStream.cs#L94

Currently, we have been forced to switch to using OnNextAsync to avoid failing unit tests.  This can have undesired performance / cost implications depending on the actual stream implementation used for the release.

**Comment by seniorquico** [comment]
A PR would be welcome!
