### ISSUE TITLE
Grain Call Filters

### ISSUE THREAD

**Issue by amcorch** [OrleansContrib/OrleansTestKit#119]
Is there any support for Grain Filters while using this test kit? I have grains that implement IIncomingGrainCallFilter, however it seems like the Invoke call is not executed when a grain method is called from my unit test.

**Comment by jkonecki** [comment]
There's no support. When you execute a method on the grain you are doing it directly. Test Silo doesn't support registering grain filters and therefore doesn't execute them. 

You can either test your grain filter separatelly, by writing a unit test for it, or execute the filter manually inside your unit test.

**Comment by seniorquico** [comment]
I agree- the TestKit is focused on testing a "simulated grain activation context", and call filters are outside this context. This is out of scope for the TestKit.
