### ISSUE TITLE
Support for Orleans 7

### ISSUE THREAD

**Issue by Badabunga** [OrleansContrib/OrleansTestKit#123]
Hi Guys, 

Love your project which makes the unit testing with Orleans very easy. 
I know that Orleans 4.0 is not released yet but we are trying to migrate our current Orleans version to the latest preview ( currently preview 2). We used this Project to build our Unit Tests for our Application. 

I am currently in the upgrading process and noticed a bunch of errors regarding reference type problems but I assume there are many more 
My Question is :  Are there any plans to support the upcoming Version ?

**Comment by seniorquico** [comment]
I haven't had an opportunity to work on an Orleans 4.0 upgrade myself. However, I think there's a lot of opportunity to _simplify_ the mock-based testing implementation given the changes. I don't think I'll have time to invest in this until shortly after the official release. I would also anticipate we'll want to create a branch specific for 4.0 compatibility, given the big differences with 3.x.

**Comment by Badabunga** [comment]
Thank you for your reply. 

Would it be okay if I would contribute a branch where I would try to migrate the current Project to the 4.0 preview 2 ? I would not try to change the current State or Architecture but rather trying to fix the current Issues regarding the upgrade ?

**Comment by seniorquico** [comment]
@Badabunga Of course! I just created a new branch named `orleans-7`. Feel free to open any pull requests against it. (Of note- it looks like they're going with Orleans 7.0 instead of 4.0 to align with the upcoming .NET release!)

**Comment by seniorquico** [comment]
Awesome progress! I started playing around with Orleans 7 over the past week, and I bumped into a number of new, tricky scenarios. There are some Orleans `internal` classes that are proving problematic.

**Comment by mayrmax** [comment]
I think the main problem are the "old" type of grains that inherit from Grain or from Grain<>, the new POCO style Grains can be easily created by just injecting the GrainContext.

**Comment by palpha** [comment]
Any chance we might see a prerelease NuGet package before long?

**Comment by bbehrens** [comment]
+1 to the prerelease test nuget question

**Comment by seniorquico** [comment]
Release to NuGet as [4.0.0-beta.1](https://www.nuget.org/packages/OrleansTestKit/4.0.0-beta.1). Thanks, @Badabunga!
