### ISSUE TITLE
How do we create new POCO grains?

### ISSUE THREAD

**Issue by michaelmcneilnet** [OrleansContrib/OrleansTestKit#127]
v4.0.0-beta1

I am trying to create a new grain with the following code

```cs
var grain = await Silo.CreateGrainAsync<MyGrain>("a");
```

but it seems the generic for `CreateGrainAsync` is constrained to type of `Grain`.

From `src/OrleansTestKit/TestKitSilo`:

```cs
 public Task<T> CreateGrainAsync<T>(string id) where T : Grain, IGrainWithStringKey =>
        CreateGrainAsync<T>(IdSpan.Create(id));
```

Is there a way to create grains that are not based on `Grain`? My grain implements `IGrainBase` instead.

**Comment by seniorquico** [comment]
@michaelmcneilnet v4.0.0 has been released to [GitHub](https://github.com/OrleansContrib/OrleansTestKit/releases/tag/4.0.0) and [NuGet](https://www.nuget.org/packages/OrleansTestKit/4.0.0) that includes support for POCO grains thanks to [spingee](https://github.com/spingee) in #130.
