### ISSUE TITLE
TimerExtensions.FireAllTimers fails if any timer subscriptions have been disposed

### ISSUE THREAD

**Issue by fergusbown** [OrleansContrib/OrleansTestKit#132]
Presumably either the below should ignore disposed timers, or TestTimer.FireAsync() should just be a no-op if the instance is disposed?

```
    public async Task FireAllAsync()
    {
        foreach (var testTimer in new List<TestTimer>(_timers))
        {
            await testTimer.FireAsync().ConfigureAwait(false);
        }
    }
```

I'm happy to make a PR obviously - not sure if there is a preference for one approach or the other?

**Comment by seniorquico** [comment]
Fixed in #129. Thanks, @spingee!
