### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by spingee** [OrleansContrib/OrleansTestKit#146]
Can you release new version so we can you it with 7.2.*?

**Comment by seniorquico** [comment]
@spingee The latest [4.0.0-beta.3](https://github.com/OrleansContrib/OrleansTestKit/releases/tag/4.0.0-beta.3) was released to NuGet with the intent to support Orleans 7.2. Are you encountering an issue with it? If yes, will you open an issue with more details?

**Comment by spingee** [comment]
Sry i overlooked it, my bad

**Comment by seniorquico** [comment]
No worries!
