### ISSUE TITLE
Please could we get a new release

### ISSUE THREAD

**Issue by fergusbown** [OrleansContrib/OrleansTestKit#147]
Would it be possible to get new packages including the merged #141 changes - thank you 👍 !!

**Comment by seniorquico** [comment]
@fergusbown v4.0.0 has been released to [GitHub](https://github.com/OrleansContrib/OrleansTestKit/releases/tag/4.0.0) and [NuGet](https://www.nuget.org/packages/OrleansTestKit/4.0.0) that includes the referenced PR.
