### ISSUE TITLE
Orleans 8 - breaking changes

### ISSUE THREAD

**Issue by jkonecki** [OrleansContrib/OrleansTestKit#149]
TestKit constructor throws the following exception after upgrading Orleans from 7.2.4 to 8.0.0.

```
System.TypeLoadException : Could not load type 'Orleans.Runtime.IKeyedServiceCollection`2' from assembly 
'Orleans.Core.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.

  Stack Trace: 
TestKitSilo.ctor()
```

I believe this is caused by this change in Orleans
**Migrate to .NET 8 keyed services** https://github.com/dotnet/orleans/issues/8590
PR: https://github.com/dotnet/orleans/pull/8725

**Comment by jkonecki** [comment]
I've created a NuGet package locally with my changes from #150 and upgraded my project that uses OrleansTestKit extensively - everything is working as expected. 
@seniorquico

**Comment by seniorquico** [comment]
Awesome! I'll run some quick tests and work on getting some new package versions out on NuGet this weekend. Thanks, @jkonecki!

**Comment by seniorquico** [comment]
@jkonecki v8.0.0 has been released to [GitHub](https://github.com/OrleansContrib/OrleansTestKit/releases/tag/8.0.0) and [NuGet](https://www.nuget.org/packages/OrleansTestKit/8.0.0). Thanks for the quick work to get the Orleans TestKit updated!
