### ISSUE TITLE
Orleans 8.1: The type initializer for 'Orleans.TestKit.Reminders.RuntimeContextManager' threw an exception.

### ISSUE THREAD

**Issue by jkonecki** [OrleansContrib/OrleansTestKit#160]
I receive the following error after upgrading to Orleans 8.1

  Message: 
```
System.TypeInitializationException : The type initializer for 'Orleans.TestKit.Reminders.RuntimeContextManager' threw an exception.
  ----> System.NullReferenceException : Object reference not set to an instance of an object.
```

  Stack Trace: 
```
RuntimeContextManager.get_Instance()
RuntimeContextScope.ctor(IGrainContext context)
RuntimeContextManager.StartExecutionContext(IGrainContext context)
TestGrainCreator.CreateGrainInstance[T](IGrainContext context)
TestKitSilo.CreateGrainAsync[T](IdSpan identity, CancellationToken cancellation)
```

I'm working on a fix.

**Comment by Laurianti** [comment]
I cannot see OrleansTestKit 8.1 on Nuget: https://www.nuget.org/packages/OrleansTestKit

Actually, the 8.0 is the latest version.

**Comment by jkonecki** [comment]
I tried to publish the package, but the Action failed as the Nugget key has
expired. I messaged the maintainers (I don't have access to Nuget account)
but they haven't fixed the issue yet.

If you're desperate, you can download the package itself from the GitHub
release page and reference it locally. I use own NuGet artifact feed in
Azure DevOps, so I can simply upload the package.
