### ISSUE TITLE
OrleansTestKit 8.1.0 not available on nuget.org

### ISSUE THREAD

**Issue by hoffmeistert** [OrleansContrib/OrleansTestKit#162]
The latest version on nuget.org is still pointing to 8.0.0.
https://www.nuget.org/packages/OrleansTestKit

Can you please push the latest version to nuget?

**Comment by jkonecki** [comment]
Project maintainers have been notified of the publishing issue.

https://github.com/OrleansContrib/OrleansTestKit/issues/160#issuecomment-2068773710

**Comment by jkonecki** [comment]
@seniorquico I'm happy to taken on a responsibility of maintaining NuGet packages - could you please add me as a package co-owner in NuGet?

**Comment by juveilko** [comment]
I would like to point out that there is a glaring problem in the 7.0 branch too, with an open PR that would fix the issue provided that a new version from 7.0 branch was published after the PR was merged.

So +1 for giving jkonecki maintaining rights!

**Comment by ReubenBond** [comment]
I've invited @jkonecki to be a maintainer.

**Comment by seniorquico** [comment]
@jkonecki already had maintainer privileges thanks to the OrleansContrib permissions.

Also of note- the 8.1.0 package was released to NuGet last week. Closing this issue.
