### ISSUE TITLE
Support Orleans 8.2

### ISSUE THREAD

**Issue by oising** [OrleansContrib/OrleansTestKit#164]
- support the new RegisterGrainTimer extension method for grains

**Comment by seniorquico** [comment]
@oising v8.2.0 has been released to [GitHub](https://github.com/OrleansContrib/OrleansTestKit/releases/tag/8.2.0) and [NuGet](https://www.nuget.org/packages/OrleansTestKit/8.2.0). Thanks for the quick work to get the Orleans TestKit updated!
