### ISSUE TITLE
create Release 8.2.1

### ISSUE THREAD

**Issue by amccool** [OrleansContrib/OrleansTestKit#167]
we have a need for a nuget containing https://github.com/OrleansContrib/OrleansTestKit/pull/165

is there any guidance for creating a release and publishing the nuget?  I see a "publish" action, but not a versioning mechanism
https://github.com/OrleansContrib/OrleansTestKit/actions/runs/10014692407

**Comment by seniorquico** [comment]
Released to NuGet as v8.2.1.
