### ISSUE TITLE
[Idea] Mock Grain Factory

### ISSUE THREAD

**Issue by dsarfati** [OrleansContrib/OrleansTestKit#18]
Add a method to setup mocked grains regardless of grain id. Currently `Silo.AddProbe` is the only way of adding a mocked out grain. It is impossible to mock a grain with an unknown id.

**Comment by jkonecki** [comment]
Good idea. I had a similar problem recently when trying to test a grain
that creates a 'child' grain to perform a subtask.

**Comment by wattsm** [comment]
I think [this PR] provides the functionality you're after? I was planning on getting it to a state where it can be merged into `master` this morning.

**Comment by wattsm** [comment]
Merged in #11.
