### ISSUE TITLE
Orleans 2 and NETStandard

### ISSUE THREAD

**Issue by martinothamar** [OrleansContrib/OrleansTestKit#28]
Hi!

I see there's some work being done to support Orleans 2.0, which is great.
I see the `0.1.4-beta` is targeting `netcoreapp2.0`, but we are using .NET 4.6.1 and so isn't compatible. Any chance this could switch to `netstandard2.0`?

**Comment by dsarfati** [comment]
I’ll take a look tonight. Don’t think there is any reason not to target netstabdard
