### ISSUE TITLE
Grain .State NullReferenceException in OnActivateAsync

### ISSUE THREAD

**Issue by martinothamar** [OrleansContrib/OrleansTestKit#34]
Using the latest 2.0.0-beta3 and getting a NullReferenceException in OnActivateAsync when trying to read or modify state from there. Looks like the private field `storage` is null on the grain object.

Reading and setting state outside of OnActivateAsync works fine. Both scenarios work fine when using the grains in a normal silo instance.

**Comment by dsarfati** [comment]
Just fixed this. There was an ordering issue in the grain lifecycle where it was getting activated before the grain state was populated. I now trigger the lifecycle events in order so it should now always have the grain state prior to being activated. 

I also included tests so we will check for this in the future.

Thanks for finding this bug and providing feedback!
