### ISSUE TITLE
Fail after upgrade projec to Orleans 2.0

### ISSUE THREAD

**Issue by AdamWyzgol** [OrleansContrib/OrleansTestKit#40]
After I upgrade our project to 2.0 I get error `Message: System.TypeLoadException : Method 'get_ServiceId' in type 'Orleans.TestKit.TestGrainRuntime' from assembly 'OrleansTestKit, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
` on all test

**Comment by dsarfati** [comment]
I haven't tried to run the 2.0 release yet. I will be working on that for our project within the next few days, and ill upgrade the test kit with anything else that i find.

**Comment by dsarfati** [comment]
2.0.0 Support was just merged in via PR #41

**Comment by raghur** [comment]
@dsarfati will you be publishing to nuget? the latest on nuget.org is still 2.0 RC2

**Comment by dsarfati** [comment]
Pushing right now. I didn't realize that Appveyor is failing to publish to Nuget.org. Not sure how to fix it so I just did it manually.

**Comment by raghur** [comment]
Looks like it wasn't pushed - Still shows 2.0 RC2 as the latest on nuget.org
