### ISSUE TITLE
NuGet 2.1.0 Package hasn't been generated/published?

### ISSUE THREAD

**Issue by el2iot2** [OrleansContrib/OrleansTestKit#44]
As mentioned [here](https://github.com/OrleansContrib/OrleansTestKit/pull/43#issuecomment-403257545), there hasn't yet been a 2.1.0 release to NuGet. Opening an issue in the hopes that I may just be hitting @dsarfati 's notification filters.

Current status in NuGet is:
![image](https://user-images.githubusercontent.com/28941195/43273305-fab9e044-90b0-11e8-98c6-9e076f3afb4d.png)

And I am hoping to decommission my fork of OrleansTestKit in a project, as I prefer to consume the nuget package. Thanks for your consideration.

**Comment by tim-f** [comment]
Hi @dsarfati!
Do you have any updates on renewing package (2.1.0) library?

**Comment by seniorquico** [comment]
It's less than ideal, but you can pull the latest NuGet package from AppVeyor:

https://ci.appveyor.com/project/dsarfati/orleanstestkit/build/artifacts

I'm going to work on automating new package deployments to NuGet in the next couple of days (waiting to get contributor access to the AppVeyor project and NuGet package). I'll leave this issue open and link the upcoming PR back to here.

**Comment by seniorquico** [comment]
AppVeyor is now configured to publish the artifacts to both NuGet and GitHub releases whenever a project maintainer tags a commit in this repository.

I just tagged 2.3.0, and the package has been successfully published!
