### ISSUE TITLE
Make the TestReminderRegistry behave more the the actual runtime ReminderRegistry

### ISSUE THREAD

**Issue by christiansparre** [OrleansContrib/OrleansTestKit#45]
Hi, we ran into a small issue using the test kit to test grain behavior when trying to unregister an unknown reminder.

On IReminderRegistry.GetReminder the TestReminderRegistry will throw a KeyNotFoundException instead of returning null as the runtime reminder registry does.

I have made the changes to support our needs and that behavior with this: https://github.com/christiansparre/OrleansTestKit/commit/69e3d9dd3fade561490c4d7ca1a709898dd13657

How does it look? Feedback for more cleanup and tests to fit the OrleansTestKit are welcome :)

PS: Thank you for an excellent unit testing library for Orleans!

**Comment by seniorquico** [comment]
Thanks, @christiansparre! Would you be interested in opening a PR for these changes?

**Comment by seniorquico** [comment]
Thanks, @christiansparre! I somehow missed the fact you already had the code ready to go! I just merged your changes into `master`.
