### ISSUE TITLE
Add the ability to reactivate a grain

### ISSUE THREAD

**Issue by srollinet** [OrleansContrib/OrleansTestKit#46]
Hi!
It seems it is not possible to reactivate a deactivated grain.
was it forgotten, or is it on purpose?

**Comment by dsarfati** [comment]
Just never went through the effort to try and recreate the reactivation workflows.

**Comment by seniorquico** [comment]
That's an interesting idea, @srollinet. Do you have an example to share that would demonstrate the use case?

**Comment by srollinet** [comment]
One of the use cases I have to test is for a monitoring grain, that periodically checks a condition.

The activation logic looks like that

```
        public override Task OnActivateAsync()
        {
            if (State.Configuration != null)
            {
                StartMonitoring();
            }
            return Task.CompletedTask;
        }
```

In this case, it would be nice to check that after deactivation, nothing happen anymore when the timers fire and that it start working again after the grain is reactivated.

As a workaround I call `OnActivateAsync()` manually on the grain. But it doesn't really simulate the full activation process.

I can also see other use cases involving resources cleaning during deactivation and where we have to ensure it works again after reactivation.

**Comment by seniorquico** [comment]
> In this case, it would be nice to check that after deactivation, nothing happen anymore when the timers fire

Do you mean that in your tests a call to `FireAllTimers` or `FireTimer` causes logic to run in a _deactivated_ grain?

> As a workaround I call `OnActivateAsync()` manually on the grain.

That shouldn't be necessary. The testkit should call both `OnActivateAsync` and `OnDeactivateAsync` methods. Check out `LifecycleGrain` and the associated tests in `BasicGrainTests`. Here's an additional example (not in the test project) that combines it all:

```cs
[Fact]
public async Task TestActivationAndDeactivation()
{
    var silo = new TestKitSilo();

    // This will call OnActivateAsync:
    var grain = await silo.CreateGrainAsync<LifecycleGrain>(new Random().Next());
    grain.ActivateCount.Should().Be(1);
    grain.DeactivateCount.Should().Be(0);

    // This will call OnDeactivateAsync:
    await silo.DeactivateAsync(grain);
    grain.ActivateCount.Should().Be(1);
    grain.DeactivateCount.Should().Be(1);
}
```

**Comment by srollinet** [comment]
> > In this case, it would be nice to check that after deactivation, nothing happen anymore when the timers fire
>
> Do you mean that in your tests a call to FireAllTimers or FireTimer causes logic to run in a deactivated grain?

No, of course not ;)

What I tried to test is something like that

```
[Fact]
public async Task TestActivationAndDeactivationAndReactivation()
{
    var silo = new TestKitSilo();

    // This will call OnActivateAsync:
    var grain = await silo.CreateGrainAsync<LifecycleGrain>(new Random().Next());

    Silo.FireAllTimers();
    // Check that the grain internal logic has been executed
   ...

    // This will call OnDeactivateAsync:
    await silo.DeactivateAsync(grain);

   Silo.FireAllTimers();
    // ensure the grain internal logic has not been executed
   ...

    // This is the method I need <--------------------
    // This will call OnActivateAsync, and maybe other methods related to storage?
    await silo.ReactivateAsync(grain);

   Silo.FireAllTimers();
    // Check that the grain internal logic has been executed normally
   ...
}
```

So as the method doesn't exist, for now I call `OnActivateAsync` manually

**Comment by seniorquico** [comment]
Got it!

I wonder if that is a desirable/valid scenario, though? Just an anecdote, but in a real silo I've noticed that an _object instance_ of the grain is not reused after a call to `OnDeactivateAsync`. Instead, a new object instance is created and then activated. I should probably dig into Orleans to confirm if that's a rule or just a coincidence-- I don't recall it being explicitly called out in the docs.

Either way, does re-activating an _object instance_ pose a problem? Isn't there the possibility that member variables contain state and the implementation assumes the values are being garbage collected after the deactivation?

I don't think the following will work (but on the bus, so can't test), but maybe a scenario like the following is a more accurate approach to emulating a real silo?

```cs
[Fact]
public async Task TestActivationAndDeactivationAndReactivation()
{
    var silo = new TestKitSilo();

    // This will call OnActivateAsync:
    var grainId = new Random().Next();
    var grainInstance1 = await silo.CreateGrainAsync<LifecycleGrain>(grainId);

    Silo.FireAllTimers();
    // Check that the grain internal logic has been executed
    ...

    // This will call OnDeactivateAsync:
    await silo.DeactivateAsync(grain);

    Silo.FireAllTimers();
    // ensure the grain internal logic has not been executed
    ...

    // This will re-activate the same (logical) grain, but this calls OnActivateAsync on a new instance.
    // This is also that part I'm not certain works. Does the same grain state instance get passed from
    // grainInstance1 to grainInstance2?
    var grainInstance2 = await silo.CreateGrainAsync<LifecycleGrain>(grainId);

    Silo.FireAllTimers();
    // Check that the grain internal logic has been executed normally
    ...
}
```

What do you think?

**Comment by seniorquico** [comment]
Relevant docs pages:

[What is a grain? (Behind the Scenes - Grain Lifecycle)](http://dotnet.github.io/orleans/Documentation/core_concepts/index.html)
[Activation Garbage Collection](http://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/activation_garbage_collection.html)

**Comment by srollinet** [comment]
Ok, thanks for the references! So it seems you are right and once the grains are deactivated, they are GC'ed
So the Reactivation logic makes no sens at all and I need to change my unit test :)

**Comment by srollinet** [comment]
That's what I feared:

> A grain has already been created in this silo. Only 1 grain per test silo should every be created. Add grain probes for supporting grains.

**Comment by seniorquico** [comment]
Yeah. But that's simply a limitation of the current testkit implementation. Let's brainstorm a pattern and a solution! :smile:

The example code I posted above seems reasonable, but it looks like an easy trap for the test writer to get it wring. You just have to know that you can't reuse the grain after the deactivation. I think it would also be slick if we could somehow detect whether the _deactivated_ grain is called from the test code, when it shouldn't be. It would be nice to come up with an API flow that makes this a bit more straightforward.

**Comment by srollinet** [comment]
> **You just have to know that you can't reuse the grain after the deactivation**. I think it would also be slick if we could somehow detect whether the deactivated grain is called from the test code, when it shouldn't be.

But on the other hand, this doesn't refect the real behavior, as in Orleans you only have a reference to a virtual grain that will be automatically and transparently recreated and activated

**Comment by seniorquico** [comment]
Sure the API to get a grain isn't the same, but I think getting the grain instance as opposed to a proxy can be advantageous in a number of "unit test" scenarios. I think "that you can't reuse the grain after the deactivation" _does_ reflect the real behavior, or it at least is close enough given the limits of mocking the runtime.

Another option is that the testkit _doesn't_ try to handle this scenario. Instead, we could view test cases that cover more complicated lifecycle workflows as requiring an "integration test" with a real runtime. The `TestCluster` in `Microsoft.Orleans.TestingHost` could handle this test case just fine going through the logical grain reference.

**Comment by dsarfati** [comment]
One possible way of supporting your use case would be to manually set the grain state prior to activating the grain. I think this would be the closest way of mimicking the true behavior of activating a grain for a 2nd time. This is just an example of what it might look like:

```cs
[Fact]
public async Task TestActivationAndDeactivationAndReactivation()
{
    var silo = new TestKitSilo();

    // This will call OnActivateAsync:
    var grainId = new Random().Next();

    // Here is the new code that would get added.
    silo.SetState(new State(){Configuration = ???})

    var grainInstance1 = await silo.CreateGrainAsync<LifecycleGrain>(grainId);
    ...
}
```

**Comment by srollinet** [comment]
@dsarfati Thanks for the tip, it is exactly what I was thinking about :)

I  close the issue as this functionality doesn't really make sens.
