### ISSUE TITLE
Change (remove?) type constraints on AddStreamProbe

### ISSUE THREAD

**Issue by skyflyer** [OrleansContrib/OrleansTestKit#48]
Currently, [AddStreamProbe](https://github.com/OrleansContrib/OrleansTestKit/blob/b5349785cf4a0691c088b26efea01121cd0f8c62/src/OrleansTestKit/Streams/StreamExtensions.cs#L8) requires reference type for the "message type" that is sent over the stream. But it should work with value types as well.

Luckily, the direct call works (so workarounds are possible):
```c#
var stream = Silo.StreamProviderManager.AddStreamProbe<Guid>(Guid.Empty, "namespace", "Default");
```

**Comment by seniorquico** [comment]
Does #42 fully address this issue?

**Comment by skyflyer** [comment]
@seniorquico, my tests are failing with the version compiled from pull request with a strange error message (` System.IO.FileNotFoundException : Could not load file or assembly 'Orleans.Core.Legacy, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`) - I suppose this could be a version mismatch issue (I compiled with the older SDK and I'm using Orleans 2.2.0). I even tried and downgraded references to Orleans.Core.Legacy in testkit to `2.2.0`, but the error persisted.

Nevertheless, if support for value types was added, it should work and you can close this issue once this is resolved.

**Comment by seniorquico** [comment]
@skyflyer The 2.3.1 release on NuGet includes the fix for streams of value types.

Let me know (preferably on #53) if you continue to have issues with the Orleans.Core.Legacy dependency.

**Comment by skyflyer** [comment]
@seniorquico, I will check it out, though it may take a couple of days until I'm able to. Will update as soon as I test it. I suppose I'll need to upgrade my dependencies to Orleans 2.3 as well...

**Comment by skyflyer** [comment]
@seniorquico, I'm sorry it took so long, but I finally got around to upgrading the dependencies and testing it out. It works, thanks!
