### ISSUE TITLE
Add support for retrieving dynamically created mocks 

### ISSUE THREAD

**Issue by jkonecki** [OrleansContrib/OrleansTestKit#63]
I'm trying to test an interaction between 2 grains - similar to Ping Pong test example.

Currently the only way to obtain a `Moq.Mock` object for the other grain (Pong) is to add the probe **before** the main gain (Ping) method executes. I use SpecFlow tests and have no way of knowing before the main grain executes what kind of verification will execute later. 

The dynamically created `Moq.Mock` instance (https://github.com/OrleansContrib/OrleansTestKit/blob/078a17bcb9268c27c4253709ac7799eb82b6933c/src/OrleansTestKit/TestGrainFactory.cs#L88) is discarded in `TestGrainFactory` as only the `.Object` is stored.

I would like to extend `TestGrainFactory` with `GetProbe` method to allow users to retrieve any probe created during the test. All `Moq.Mock` objects will be stored in `Dictionary<string, Moq.Mock> _probeMocks` collection.

**Comment by jkonecki** [comment]
Actually I've found the way of obtaining a `Mock` instance from the mocked object:

`Mock<IGrainInterface> mock = Moq.Mock<IGrainInterface>.Get(grain);`

**Comment by seniorquico** [comment]
Thanks for the question and solution!

I know we're lacking docs in this project. I'm hoping to get started on some soon. I'll review issues, like these, to make sure we get some good examples in the docs for reference.
