### ISSUE TITLE
How to test GetPrimaryKeyLong?

### ISSUE THREAD

**Issue by Ilchert** [OrleansContrib/OrleansTestKit#73]
I am trying to mock some code with `GetPrimaryKeyLong` call and can't come to success. `IActivationData Data` inside grain is `null`.

**Comment by seniorquico** [comment]
Yes, this is a [known limitation](https://github.com/OrleansContrib/OrleansTestKit/blob/master/README.md#known-limitations). See #47 for additional information.

The _potential_ workaround is to force a `GetPrimaryKey` extension method call that doesn't use `IActivationData`.

Feel free to re-open with more specific code examples.
