### ISSUE TITLE
Await FireTimer

### ISSUE THREAD

**Issue by Ilchert** [OrleansContrib/OrleansTestKit#75]
In Orleans, timer callback returns `Task`, but in test framework, we can't await them, can we add `FireAllTimersAsync`?

**Comment by seniorquico** [comment]
Yes, we should definitely be awaiting the task.

We can add a `Task`-based fire method and annotate the existing (broken) method with `[Obsolete]` for backwards compatibility. I don't think we should fix the current `Fire` method, as existing projects may be depending on its quirky behavior.
