### ISSUE TITLE
Argument issue on CreateGrainAsync

### ISSUE THREAD

**Issue by RetroMechanics** [OrleansContrib/OrleansTestKit#78]
Hi!

The function `CreateGrainAsync` systematically returns an `ArgumentException` to me when I try to create a grain. My grain extends `Orleans.IGrainWithIntegerKey`.

When I do:
`var grain = await Silo.CreateGrainAsync<IHelloGrain>(0L);`
I have this error: `error CS1503: Argument 1: cannot convert from' long' to' System.Guid' `

If I try to use a `System.Guid`, I have an `Argument 1: cannot convert from 'System.Guid' to 'long'`, which seems logical.

I use Orleans 2.3.5 and TestKit 2.3.5.

My complete code:

```
// IHelloGrain.cs
public interface IHelloGrain : Orleans.IGrainWithIntegerKey
{
    Task<string> SayHello(string greeting);
}

// HelloGrain.cs
public class HelloGrain : Orleans.Grain, IHelloGrain
{
    public Task<string> SayHello(string greeting)
    {
        return Task.FromResult($"You said: '{greeting}', I say: Hello!");
    }
}

// HelloGrainTest.cs
[Fact]
public async Task CreateGrain()
{
    var grain = await Silo.CreateGrainAsync<IHelloGrain>(0L);
    grain.Service.Should().NotBeNull();
}
```

Is it a known issue or something wrong with my code?

**Comment by dsarfati** [comment]
When using the test kit you need to pass the grain class, not the interface into the ’CreateGrainAsync’ method. This allows you to test an explicit implementation of your grain.

**Comment by RetroMechanics** [comment]
That was it, thanks for your help.
