### ISSUE TITLE
Breaking change in Orleans 3.1.2

### ISSUE THREAD

**Issue by Ilchert** [OrleansContrib/OrleansTestKit#88]
[One more](https://github.com/dotnet/orleans/commit/4f436b2cf070448bc4e3d3592b0a69d870001916#diff-dab0f58c162c0f58a0d36f971fb31a77L33) breaking change in Orleans. Removed `RegistrationStrategy` from `IGrainActivationContext` in master, but [still exists](https://github.com/dotnet/orleans/blob/v3.1.2/src/Orleans.Core/Runtime/IGrainActivationContext.cs) in latest stable version 3.1.2.

**Comment by Hechamon** [comment]
That was already in 3.1.1, V3.1 of the testkit should handle that aswell, or does it not?
https://github.com/OrleansContrib/OrleansTestKit/commit/1bf9ec295c38e29a6720d33e7d36e9ceb82849b9#diff-318120cf60278306f8489a8bfbda0d9a

**Comment by Ilchert** [comment]
It looks like some bug in nuget package. 
![image](https://user-images.githubusercontent.com/13449633/75984991-7f602b80-5efc-11ea-8ee7-92b571de52a6.png)

**Comment by Ilchert** [comment]
No, the method still exists in [source code](https://github.com/dotnet/orleans/blob/v3.1.2/src/Orleans.Core/Runtime/IGrainActivationContext.cs)

**Comment by Hechamon** [comment]
I see, what was released as Version 3.1.1 was a broken release which removed the Strategy. So Testkit 3.1.0 works with 3.1.1, but not with 3.1 or 3.1.2 🙄

The fix should be easy, just revert the change above, and then it should work again.

**Comment by Hechamon** [comment]
So maybe there should be a Testkit Version 3.1.2 which is compatible with Orleans >3.1.2?

**Comment by Ilchert** [comment]
It will be nice to have the same versions as Orleans

**Comment by seniorquico** [comment]
Just an FYI... It's not practical to stay in-sync with Orleans version numbers. There are times where Orleans updates and we don't need to update (no breaking API changes), and there are times where Orleans doesn't update and we do (fixing bugs, adding new features).

I've been trying to stick with the same major & minor version components. I think we should just continue with something like Olreans vA.B.X and OrleansTestKit vA.B.Y. Sometimes X == Y, but we really can't force it.
