### ISSUE TITLE
Removed `sealed` keyword

### ISSUE THREAD

**Issue by jkonecki-techfabric** [OrleansContrib/OrleansTestKit#92]
Several key classes (`StorageManager`, `TestStorage`, `TestKitSilo`) are marked as `sealed`.

This means their behaviour cannot be customized.

I'm currently using a storage provider and grains that are event-sourced, and need custom behaviour around state handling (state is not just a single object, it's a stream of events). I also want to allow for richer tests when reading / writing state.

The alternative is to fork the whole project, wchich I would like to avoid.

Would you please consider dropping `sealed` keywords? I'm happy to make a PR.

It's a bit urgent for me, so would hugely appreciate your response.

**Comment by seniorquico** [comment]
@jkonecki-techfabric Sounds fine to me. But is `sealed` enough? Are there methods that would also need to be marked `virtual`? If you can, take a pass over the classes and submit a PR.

I believe the last release process ran fully automated. Publishing a new version on NuGet should be as simple as tagging the desired commit after the PR is merged.

**Comment by jkonecki-techfabric** [comment]
Yes, TestStorage methods would be virtual. I'll make a PR shortly.

Thank you very much for a prompt response!
________________________________
