### ISSUE TITLE
Need a new version for v3.3.0 support

### ISSUE THREAD

**Issue by pentp** [OrleansContrib/OrleansTestKit#95]
https://github.com/dotnet/orleans/pull/6580 added a new property for `IStorage<TState>` which is not implemented by current version of TestKit:
`System.TypeLoadException: Method 'get_RecordExists' in type 'Orleans.TestKit.Storage.TestStorage' from assembly 'OrleansTestKit, Version=3.1.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation..`

This property will be included in v3.3.0 by https://github.com/dotnet/orleans/pull/6686

**Comment by seniorquico** [comment]
Released as 3.1.3. I opened https://github.com/OrleansContrib/OrleansTestKit/issues/98 as a follow-up. We should be able to provide a working implementation of the `RecordExists` property.
