### ISSUE TITLE
Implement RecordExists

### ISSUE THREAD

**Issue by seniorquico** [OrleansContrib/OrleansTestKit#98]
The TestStorage should implement the new `RecordExists` property introduced in Orleans 3.3.0. A call to `WriteStateAsync` should set `RecordExists` to `true`, and a call to `ClearStateAsync` should set `RecordExists` to `false.

See the discussion notes on https://github.com/OrleansContrib/OrleansTestKit/pull/96.

**Comment by zeus82** [comment]
I took a crack at it see - https://github.com/OrleansContrib/OrleansTestKit/pull/99

**Comment by seniorquico** [comment]
Added in #99.
